### PR TITLE
fix: ignoring password when user forgot it on wallet reset

### LINKED ISSUE #246: "forgot my password"
when we are trying to  delete a wallet, if we  insert the wrong password and then click "forgot my password" it wont work, the modal has to be closed and check "forgot password" again without trying to submit it above

### PR DESCRIPTION
**Pull request by tuliomir**
### Acceptance Criteria
- Form should ignore the password field if the "Forgot password" checkbox is selected.
- Fixes #246 

### Other improvements
**When the "Forgot Password" checkbox is selected, the "Password" field is cleared and disabled.**
[Example video](https://user-images.githubusercontent.com/1299409/149586640-4f10fcec-36f9-488b-b958-d309e5ec0987.mp4)

**When the user closes the modal, all its fields are cleared.**
https://user-images.githubusercontent.com/1299409/149586712-ec26344c-677f-4264-8860-e3eff63e6c44.mp4

### Security Checklist
- [x] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

### CODE REVIEW

File: src/components/ModalResetAllData.js [hunk 1]
```diff
@@ -32,26 +32,60 @@ class ModalResetAllData extends React.Component {
...
+    if (password && !correctPassword) {
+      this.setState({errorMessage: t`Invalid password`})
+      return
+    }
+
+    // Password was informed and correct OR password was forgotten: we can proceed to wallet reset.
+    this.props.success()
+  }
+
+  setForgotPassword = (e) => {
```
Comment (pedroferreira1) [inline src/components/ModalResetAllData.js:69]: Missing docstring

File: src/components/ModalResetAllData.js [hunk 2]
```diff
@@ -32,26 +32,60 @@ class ModalResetAllData extends React.Component {
...
+    this.setState(state => ({forgotPassword: !state.forgotPassword}))
+
+    // Clearing password field if the user did forget it
+    if (!this.state.forgotPassword) {
+      this.refs.password.value = ''
     }
   }
 
+  onDismiss = (e) => {
```
Comment (pedroferreira1) [inline src/components/ModalResetAllData.js:78]: Missing docstring

**Review by pedroferreira1 — APPROVED** [review]

**Review by andreabadesso — APPROVED** [review]
