### PR TITLE
fix(i18n): Missing key props in some places

### LINKED ISSUE #75: Missing unique "key" prop when using str2jsx function
`str2jsx` (for i18n) returns an array with elements. Following react guidelines, each should have a unique key. Example stacktrace: 

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Settings`. See https://fb.me/react-warning-keys for more information.
    in a (at Settings.js:143)
    in Settings (at App.js:319)
    in div (at App.js:317)
    in Route (at App.js:300)
    in StartedRoute (at App.js:195)
    in Switch (at App.js:189)
    in Root (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at ErrorWrapper.js:51)
    in ErrorBoundary (at ErrorWrapper.js:67)
    in Route (at ErrorWrapper.js:70)
    in div (at ErrorWrapper.js:69)
    in ErrorWrapper (created by Context.Consumer)
    in Route (at src/index.js:25)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:24)
    in Provider (at src/index.js:23)
```

### PR DESCRIPTION
**Pull request by msbrogli**
Closes #75

### CODE REVIEW

File: src/components/TxTextInput.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ const TxTextInput = (props) => {
       <span>{props.helpText}</span>
       <textarea rows="5" onChange={props.onChange}></textarea>
       <span>{str2jsx(t`Click |link:here| to ${props.otherAction} this transaction`,
-                     {link: (x) => <Link to={props.link}>{x}</Link>})}
+                     {link: (x, i) => <Link key={i} to={props.link}>{x}</Link>})}
```
Comment (msbrogli) [inline src/components/TxTextInput.js]: Update docstring recommending to always use the `key` props.

Comment (msbrogli) [reply src/components/TxTextInput.js]: It was already explained in the docstring.
